### ISSUE TITLE
Linking issues

### ISSUE THREAD

**Issue by poojagaonkar** [KarinBerg/Xamarin.HEREMaps#3]
Hi, 

I am trying to create a basic functionality with using the binding. But when I try to build the project it does not build and gives multiple errors :-

`MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAARBillboardObject. The symbol '_OBJC_CLASS_$_NMAARBillboardObject' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAARCameraParameters. The symbol '_OBJC_CLASS_$_NMAARCameraParameters' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAARController. The symbol '_OBJC_CLASS_$_NMAARController' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAARIconObject. The symbol '_OBJC_CLASS_$_NMAARIconObject' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAARModelObject. The symbol '_OBJC_CLASS_$_NMAARModelObject' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAARObject. The symbol '_OBJC_CLASS_$_NMAARObject' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAARPolylineObject. The symbol '_OBJC_CLASS_$_NMAARPolylineObject' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAARPoseReading. The symbol '_OBJC_CLASS_$_NMAARPoseReading' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAAdasisV2Engine. The symbol '_OBJC_CLASS_$_NMAAdasisV2Engine' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAAdasisV2MessageConfiguration. The symbol '_OBJC_CLASS_$_NMAAdasisV2MessageConfiguration' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAAddress. The symbol '_OBJC_CLASS_$_NMAAddress' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAAddressFilter. The symbol '_OBJC_CLASS_$_NMAAddressFilter' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAApplicationContext. The symbol '_OBJC_CLASS_$_NMAApplicationContext' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAAudioFileOutput. The symbol '_OBJC_CLASS_$_NMAAudioFileOutput' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAAudioManager. The symbol '_OBJC_CLASS_$_NMAAudioManager' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAAudioOutput. The symbol '_OBJC_CLASS_$_NMAAudioOutput' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAAutoSuggest. The symbol '_OBJC_CLASS_$_NMAAutoSuggest' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAAutoSuggestPlace. The symbol '_OBJC_CLASS_$_NMAAutoSuggestPlace' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAAutoSuggestQuery. The symbol '_OBJC_CLASS_$_NMAAutoSuggestQuery' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAAutoSuggestSearch. The symbol '_OBJC_CLASS_$_NMAAutoSuggestSearch' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAAutoSuggestionRequest. The symbol '_OBJC_CLASS_$_NMAAutoSuggestionRequest' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMABasicClusterStyle. The symbol '_OBJC_CLASS_$_NMABasicClusterStyle' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMACategory. The symbol '_OBJC_CLASS_$_NMACategory' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMACategoryFilter. The symbol '_OBJC_CLASS_$_NMACategoryFilter' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMACategoryGraphRequest. The symbol '_OBJC_CLASS_$_NMACategoryGraphRequest' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAClusterLayer. The symbol '_OBJC_CLASS_$_NMAClusterLayer' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAClusterStyle. The symbol '_OBJC_CLASS_$_NMAClusterStyle' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAClusterTheme. The symbol '_OBJC_CLASS_$_NMAClusterTheme' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAClusterViewObject. The symbol '_OBJC_CLASS_$_NMAClusterViewObject' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMACompositeView. The symbol '_OBJC_CLASS_$_NMACompositeView' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAContactDetail. The symbol '_OBJC_CLASS_$_NMAContactDetail' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMACoreRouter. The symbol '_OBJC_CLASS_$_NMACoreRouter' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMACountryInfo. The symbol '_OBJC_CLASS_$_NMACountryInfo' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMACustomConfigurations. The symbol '_OBJC_CLASS_$_NMACustomConfigurations' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMACustomizableColor. The symbol '_OBJC_CLASS_$_NMACustomizableColor' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMACustomizableScheme. The symbol '_OBJC_CLASS_$_NMACustomizableScheme' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMACustomizableVariable. The symbol '_OBJC_CLASS_$_NMACustomizableVariable' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMADevicePositionSource. The symbol '_OBJC_CLASS_$_NMADevicePositionSource' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMADirectionalLight. The symbol '_OBJC_CLASS_$_NMADirectionalLight' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMADiscoveryLink. The symbol '_OBJC_CLASS_$_NMADiscoveryLink' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMADiscoveryPage. The symbol '_OBJC_CLASS_$_NMADiscoveryPage' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMADiscoveryRequest. The symbol '_OBJC_CLASS_$_NMADiscoveryRequest' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMADynamicPenalty. The symbol '_OBJC_CLASS_$_NMADynamicPenalty' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAEHLink. The symbol '_OBJC_CLASS_$_NMAEHLink' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAEHLinkInformation. The symbol '_OBJC_CLASS_$_NMAEHLinkInformation' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAEHLinkRange. The symbol '_OBJC_CLASS_$_NMAEHLinkRange' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAEHMapAccessor. The symbol '_OBJC_CLASS_$_NMAEHMapAccessor' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAEHMetaData. The symbol '_OBJC_CLASS_$_NMAEHMetaData' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAEHPathTree. The symbol '_OBJC_CLASS_$_NMAEHPathTree' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAEHPathTreeRange. The symbol '_OBJC_CLASS_$_NMAEHPathTreeRange' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAEHPosition. The symbol '_OBJC_CLASS_$_NMAEHPosition' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAEHSlopeDataPoint. The symbol '_OBJC_CLASS_$_NMAEHSlopeDataPoint' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAElectronicHorizon. The symbol '_OBJC_CLASS_$_NMAElectronicHorizon' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAExtendedAttribute. The symbol '_OBJC_CLASS_$_NMAExtendedAttribute' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAFleetConnectivityCustomEvent. The symbol '_OBJC_CLASS_$_NMAFleetConnectivityCustomEvent' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAFleetConnectivityCustomMessage. The symbol '_OBJC_CLASS_$_NMAFleetConnectivityCustomMessage' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAFleetConnectivityError. The symbol '_OBJC_CLASS_$_NMAFleetConnectivityError' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAFleetConnectivityEvent. The symbol '_OBJC_CLASS_$_NMAFleetConnectivityEvent' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAFleetConnectivityIssue. The symbol '_OBJC_CLASS_$_NMAFleetConnectivityIssue' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAFleetConnectivityJobCancelledEvent. The symbol '_OBJC_CLASS_$_NMAFleetConnectivityJobCancelledEvent' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAFleetConnectivityJobFinishedEvent. The symbol '_OBJC_CLASS_$_NMAFleetConnectivityJobFinishedEvent' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAFleetConnectivityJobMessage. The symbol '_OBJC_CLASS_$_NMAFleetConnectivityJobMessage' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAFleetConnectivityJobRejectedEvent. The symbol '_OBJC_CLASS_$_NMAFleetConnectivityJobRejectedEvent' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAFleetConnectivityJobStartedEvent. The symbol '_OBJC_CLASS_$_NMAFleetConnectivityJobStartedEvent' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAFleetConnectivityMessage. The symbol '_OBJC_CLASS_$_NMAFleetConnectivityMessage' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAFleetConnectivityService. The symbol '_OBJC_CLASS_$_NMAFleetConnectivityService' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAGeoBoundingBox. The symbol '_OBJC_CLASS_$_NMAGeoBoundingBox' could not be found in any of the libraries or frameworks linked with your application.
    		
    MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: NMAGeoCoordinates. The symbol '_OBJC_CLASS_$_NMAGeoCoordinates' could not be found in any of the libraries or frameworks linked with your application.
    		
`

These are few of them. I have selected Linker behaviour to be "Link framework and sdks only" and supported architectures to be x86_64.

Can you please help me out here?

**Comment by TomQv** [comment]
@poojagaonkar Did you solve the issue? How?

**Comment by poojagaonkar** [comment]
@TomQv  As far as I remember, I built the project on a real device rather than building it on a simulator and it seemed to work.

**Comment by TomQv** [comment]
@poojagaonkar Ok, I'm having the issue on both, simulator and real device.
